### ISSUE TITLE
clean up

### ISSUE THREAD

**Issue by elianiva** [siduck76/pomoReward#2]
https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/index.html#L42-L48

probably want to add `cursor: pointer` so the user would know if it's clickable

---

https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/miscFuncs.js#L15-L17

https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/buttonClickActions.js#L103-L105

I would change it to this because it's shorter and it would be still readable.

```javascript
const timerSound = () => document.getElementById("dingding").play(); 
// ---
(temp) => (temp.style.display = "none")
```
 
 ---
 
https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/miscFuncs.js#L25-L31
https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/buttonClickActions.js#L56

I would avoid changing external stuff like `pomoBox.innerText` from here, A.K.A "side effect". I think it would be better if you return a string and do something like `pomoBox.innerText = boxText(totalTime, 0)`. You might want to read some articles about "pure function".

I'd do this instead which you can then use by doing `pomoBox.innerText = boxText(totalTime, 0)`

```javascript
const boxText = (min, sec) => {
  if (min < 10) return `0${min} : ${sec}`
  if (sec < 10) return `${min} : 0${sec}`
  return `${min} : ${sec}`
}
```

You might also want to change the variable name to `getBoxText` or something like that because it's only getting the time string and nothing else, but of course it's up to you.

---

https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/buttonClickActions.js#L51-L65

you could do something like this instead.

```javascript
 if (temp.className === "reset") { 
   currentClick = "reset"; 
   clearInterval(timer); 
  
   pomoTime = totalTime * 60; 
   boxText(totalTime, 0); 
  return
} 
  
playTickSound(); 
currentClick = temp.className === "start" ? "start" : "restart"
```

---

https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/buttonClickActions.js#L62-L64

You could do something like this instead.

```javascript
currentClick = temp.className === "start" ? "start" : "restart";
```

---

https://github.com/siduck76/pomoReward/blob/b1e73af9f2b9137fbd2b5e162caa285a6fd847cd/js_src/modules/miscFuncs.js#L34

I think this isn't necessary? Because you only use it on one place and you can just replace it with `pomoBox.innerText = "someting"`

---

Hope you don't mind with what I said, that's not all of them but I think that's a fair amount. I'll continue if you want. Of course feel free to ignore what I said if you don't agree :)

**Comment by siduck76** [comment]
thanks! Ive changed all of them except the last one , I will have the need to use it for displaying error in multiple errors soon so I made a function for it , and yeah continue on more :)

**Comment by elianiva** [comment]
https://github.com/siduck76/pomoReward/blob/aff0c11bbb15fa84b1fa29a63707458f518e02a0/js_src/modules/miscFuncs.js#L23-L31

I think you want to make this function behave differently if you decide to rename it to `getBoxText`. `get` is indicating that the function will return something. Either you want to change its behaviour or keep the current behaviour and rename it to `setBoxText`.

**Comment by siduck76** [comment]
thx, I changed it
